"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { useParams } from "next/navigation";
import { authedFetch } from "@/lib/api";
import AdminShell from "@/components/AdminShell";

type Data={booking:any;tourist:any;local:any;service:any;economics:{local_amount:number;platform_fee:number;customer_total:number};messages:any[];review:any;meeting_point:any;timeline:any[];end_time:string;payment:any};
export default function Page(){
 const params=useParams<{id:string}>();const [d,setD]=useState<Data|null>(null);const [status,setStatus]=useState('Loading booking…');const [meeting,setMeeting]=useState<any>({meeting_point_name:'',meeting_address:'',meeting_instructions:''});
 async function load(){const r=await authedFetch(`/api/admin/bookings/${params.id}`);const j=await r.json().catch(()=>({}));if(!r.ok){setStatus(j.detail||'Could not load booking');return}setD(j);setMeeting(j.meeting_point||{});setStatus('')}
 useEffect(()=>{load()},[params.id]);
 async function update(next:string){const r=await authedFetch(`/api/admin/bookings/${params.id}`,{method:'PATCH',body:JSON.stringify({status:next})});const j=await r.json().catch(()=>({}));if(!r.ok)setStatus(j.detail||'Update failed');else await load()}
 async function saveMeeting(){const r=await authedFetch(`/api/bookings/${params.id}/meeting-point`,{method:'PATCH',body:JSON.stringify({...meeting,latitude:null,longitude:null})});const j=await r.json().catch(()=>({}));if(!r.ok)setStatus(j.detail||'Could not save meeting point');else{setStatus('Meeting point saved.');await load()}}
 return <AdminShell eyebrow="Booking operations" title={`Booking #${params.id}`}><div className="detail-breadcrumb"><Link href="/admin/bookings">← Back to bookings</Link></div>{status&&<div className="notice">{status}</div>}{d&&<div className="admin-detail-grid"><section className="admin-detail-stack">
 <div className="detail-card"><div className="admin-detail-head"><div><div className="status-stack"><span className={`badge status-${d.booking.status}`}>{d.booking.status}</span><span className={`badge payment-${d.payment?.status||'manual'}`}>{String(d.payment?.status||'manual').replaceAll('_',' ')}</span></div><h3>{d.service?.title||'General local booking'}</h3><p className="muted">{d.booking.booking_date} · {d.booking.start_time}–{d.end_time} · {d.booking.hours} hr · {d.booking.guests} guest(s)</p></div><strong className="booking-detail-total">${d.economics.customer_total.toFixed(2)}</strong></div>{d.booking.message&&<div className="admin-note-block"><strong>Traveler request</strong><p>{d.booking.message}</p></div>}</div>
 <div className="admin-two-col"><div className="detail-card"><h3>Traveler</h3><p><strong>{d.tourist.name}</strong></p><p>{d.tourist.email}</p><p>{d.tourist.phone||'No phone added'}</p><p className="muted">{[d.tourist.home_city,d.tourist.country].filter(Boolean).join(', ')||'Location not added'}</p></div><div className="detail-card"><h3>Local</h3><p><strong>{d.local.name}</strong> {d.local.verified?'✓':''}</p><p>{d.local.email}</p><p>{d.local.city}</p>{d.local.slug&&<Link className="admin-text-link" href={`/locals/${d.local.slug}`}>Open public profile</Link>}</div></div>
 <div className="detail-card"><h3>Meeting point</h3><div className="meeting-edit-grid"><input value={meeting.meeting_point_name||''} onChange={e=>setMeeting({...meeting,meeting_point_name:e.target.value})} placeholder="Meeting point / landmark"/><input value={meeting.meeting_address||''} onChange={e=>setMeeting({...meeting,meeting_address:e.target.value})} placeholder="Address"/><textarea value={meeting.meeting_instructions||''} onChange={e=>setMeeting({...meeting,meeting_instructions:e.target.value})} placeholder="Instructions" rows={2}/><button className="mini-btn" onClick={saveMeeting}>Save meeting point</button></div></div>
 <div className="detail-card"><h3>Lifecycle timeline</h3>{d.timeline?.length?<div className="booking-timeline">{d.timeline.map(e=><div className="timeline-row" key={e.id}><span className="timeline-dot"/><div><strong>{e.event_type.replaceAll('_',' ')}</strong><p>{e.note}</p><small>{e.actor_name} ({e.actor_role}) · {new Date(e.created_at).toLocaleString()}</small></div></div>)}</div>:<p className="muted">No lifecycle events recorded yet.</p>}</div>
 <div className="detail-card"><h3>Conversation</h3>{d.messages.length?<div className="admin-message-list">{d.messages.map(m=><article key={m.id}><strong>{m.sender_name} <span>{m.sender_role}</span></strong><p>{m.body}</p><small>{new Date(m.created_at).toLocaleString()}</small></article>)}</div>:<p className="muted">No messages in this booking yet.</p>}</div>{d.review&&<div className="detail-card"><h3>Review</h3><strong>★ {d.review.rating}/5 · {d.review.title||'Review'}</strong><p>{d.review.comment}</p></div>}</section>
 <aside className="detail-card sticky admin-operation-card"><h3>Economics</h3><div className="price-lines"><span><i>Local amount</i><strong>${d.economics.local_amount.toFixed(2)}</strong></span><span><i>Platform fee</i><strong>${d.economics.platform_fee.toFixed(2)}</strong></span><span className="price-total"><i>Customer total</i><strong>${d.economics.customer_total.toFixed(2)}</strong></span></div><div className="payment-system-box"><strong>Payment: {String(d.payment?.status||'manual').replaceAll('_',' ')}</strong><span>Mode: {d.payment?.mode||'manual'}</span><span>Currency: {d.payment?.currency||'USD'}</span>{d.payment?.payment_intent_id&&<span>PaymentIntent: {d.payment.payment_intent_id}</span>}{d.payment?.status==='paid'&&<Link className="mini-btn secondary-mini" href="/admin/payments">Refund / payment operations</Link>}</div><div className="admin-status-actions"><button className="btn" onClick={()=>update('confirmed')}>Confirm</button><button className="btn secondary" disabled={Boolean(d.payment?.required&&d.payment?.status!=='paid')} onClick={()=>update('completed')}>Mark completed</button><button className="btn booking-cancel-btn" disabled={Boolean(d.payment?.required&&d.payment?.status==='paid')} onClick={()=>update('cancelled')}>Cancel booking</button></div><p className="muted booking-policy-note">Admin overrides are recorded in the lifecycle timeline.</p></aside></div>}</AdminShell>
}

