"use client";
import Link from "next/link";
import { FormEvent,useEffect,useState } from "react";
import { useParams } from "next/navigation";
import { authedFetch } from "@/lib/api";

type Meeting={meeting_point_name:string;meeting_address:string;meeting_instructions:string;latitude?:number|null;longitude?:number|null};
type Payment={provider:string;mode:string;required:boolean;currency:string;status:string;amount_total:number|null;platform_fee:number|null;refunded_amount:number;paid_at?:string|null};
type Booking={id:number;booking_date:string;start_time:string;end_time:string;guests:number;hours:number;message:string;subtotal:number;platform_fee:number;total:number;status:string;local_name:string;local_slug:string;local_headline:string;local_city:string;local_image:string;service_title:string;service_category:string;message_count:number;meeting_point:Meeting;timeline:any[];review:any;payment:Payment};
export default function Page(){
 const params=useParams<{id:string}>();const id=Number(params.id);const [b,setB]=useState<Booking|null>(null);const [status,setStatus]=useState('Loading booking…');const [busy,setBusy]=useState(false);const [meeting,setMeeting]=useState<Meeting>({meeting_point_name:'',meeting_address:'',meeting_instructions:''});
 async function load(){const r=await authedFetch(`/api/traveler/bookings/${id}`);const d=await r.json().catch(()=>({}));if(!r.ok){setStatus(d.detail||'Could not load booking');return}setB(d);setMeeting(d.meeting_point||{meeting_point_name:'',meeting_address:'',meeting_instructions:''});setStatus('')}
 useEffect(()=>{if(id)load()},[id]);
 async function cancel(){if(!confirm('Cancel this booking request?'))return;setBusy(true);const r=await authedFetch(`/api/traveler/bookings/${id}/cancel`,{method:'PATCH'});const d=await r.json().catch(()=>({}));if(!r.ok){setStatus(d.detail||'Could not cancel booking')}else await load();setBusy(false)}
 async function pay(){setBusy(true);setStatus('Opening secure Safepay checkout…');const r=await authedFetch(`/api/payments/bookings/${id}/checkout`,{method:'POST'});const d=await r.json().catch(()=>({}));if(!r.ok){setStatus(d.detail||'Could not start payment');setBusy(false);return}if(d.already_paid){setStatus('Payment is already confirmed.');await load();setBusy(false);return}if(d.checkout_url){window.location.href=d.checkout_url;return}setBusy(false)}
 async function saveMeeting(){setBusy(true);setStatus('Saving meeting point…');const r=await authedFetch(`/api/bookings/${id}/meeting-point`,{method:'PATCH',body:JSON.stringify({...meeting,latitude:null,longitude:null})});const d=await r.json().catch(()=>({}));if(!r.ok)setStatus(d.detail||'Could not save meeting point');else{await load();setStatus('Meeting point updated.')}setBusy(false)}
 async function review(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);const r=await authedFetch('/api/traveler/reviews',{method:'POST',body:JSON.stringify({booking_id:id,rating:Number(f.get('rating')),title:String(f.get('title')||''),comment:String(f.get('comment')||'')})});const d=await r.json().catch(()=>({}));if(!r.ok){setStatus(d.detail||'Could not submit review')}else{setStatus('Review published. Thank you.');await load()}setBusy(false)}
 if(!b)return <>{status&&<div className="notice">{status}</div>}</>;
 const payment=b.payment||{provider:'manual',mode:'manual',required:false,currency:'USD',status:'manual',amount_total:null,platform_fee:null,refunded_amount:0};
 const paid=payment.status==='paid'; const canPay=payment.required&&b.status==='confirmed'&&!paid&&!['refunded','refund_pending'].includes(payment.status);
 return <><div className="detail-breadcrumb"><Link href="/dashboard/bookings">← My bookings</Link><span>Booking #{b.id}</span></div><div className="booking-detail-head"><div><div className="status-stack"><span className={`badge status-${b.status}`}>{b.status}</span><span className={`badge payment-${payment.status}`}>{paymentLabel(payment.status)}</span></div><h2>{b.service_title}</h2><p className="muted">Booking with {b.local_name} in {b.local_city}</p></div><strong className="booking-detail-total">${b.total.toFixed(2)}</strong></div>{status&&<div className="notice">{status}</div>}
 <div className="booking-detail-grid"><section><article className="detail-card local-summary-card"><Link href={`/locals/${b.local_slug}`}><img src={b.local_image} alt={b.local_name}/></Link><div><Link href={`/locals/${b.local_slug}`}><h3>{b.local_name}</h3></Link><p>{b.local_headline}</p><span className="muted">{b.local_city}</span></div></article>
 <article className="detail-card"><h3>Trip details</h3><div className="detail-facts"><span><strong>Date</strong>{b.booking_date}</span><span><strong>Time</strong>{b.start_time}–{b.end_time}</span><span><strong>Duration</strong>{b.hours} hours</span><span><strong>Guests</strong>{b.guests}</span><span><strong>Category</strong>{b.service_category}</span><span><strong>Booking ID</strong>#{b.id}</span></div>{b.message&&<div className="traveler-note"><strong>Your note to the local</strong><p>{b.message}</p></div>}</article>
 <article className="detail-card payment-card"><div className="payment-card-head"><div><h3>Payment</h3><p className="muted">{payment.required?('Secure payment is handled by Safepay after the local confirms your request.'):'This environment is using manual payment mode.'}</p></div><span className={`badge payment-${payment.status}`}>{paymentLabel(payment.status)}</span></div><div className="payment-facts"><span><strong>Provider</strong>{payment.required?'Safepay Hosted Checkout':'Manual'}</span><span><strong>Currency</strong>{payment.currency||'USD'}</span><span><strong>Total</strong>${b.total.toFixed(2)}</span><span><strong>Refunded</strong>${(payment.refunded_amount||0).toFixed(2)}</span></div>{canPay&&<button className="btn" onClick={pay} disabled={busy}>{busy?'Opening checkout…':`Pay $${b.total.toFixed(2)} securely`}</button>}{payment.required&&b.status==='pending'&&<div className="notice">Payment unlocks after the local accepts this booking.</div>}{paid&&<div className="notice">Payment confirmed. Your local can complete the booking after the experience.</div>}{payment.status==='refunded'&&<div className="notice">This payment has been refunded.</div>}</article>
 <article className="detail-card"><div className="meeting-panel-head"><div><h3>Meeting point</h3><p className="muted">Keep the exact meeting location inside the booking.</p></div></div>{b.status==='pending'?<div className="meeting-edit-grid"><input value={meeting.meeting_point_name||''} onChange={e=>setMeeting({...meeting,meeting_point_name:e.target.value})} placeholder="Meeting point / landmark"/><input value={meeting.meeting_address||''} onChange={e=>setMeeting({...meeting,meeting_address:e.target.value})} placeholder="Address"/><textarea value={meeting.meeting_instructions||''} onChange={e=>setMeeting({...meeting,meeting_instructions:e.target.value})} placeholder="Exact instructions" rows={2}/><button className="mini-btn" disabled={busy} onClick={saveMeeting}>Save meeting point</button></div>:<MeetingSummary meeting={b.meeting_point}/>}</article>
 <article className="detail-card"><h3>Booking timeline</h3>{b.timeline?.length?<div className="booking-timeline">{b.timeline.map((e:any)=><div className="timeline-row" key={e.id}><span className="timeline-dot"/><div><strong>{eventLabel(e)}</strong><p>{e.note}</p><small>{e.actor_name} · {new Date(e.created_at).toLocaleString()}</small></div></div>)}</div>:<p className="muted">Timeline events will appear as this booking progresses.</p>}</article>
 {b.status==='completed'&&<article className="detail-card" id="review"><h3>Your review</h3>{b.review?<div className="published-review"><div className="review-stars">{'★'.repeat(b.review.rating)}{'☆'.repeat(5-b.review.rating)}</div><strong>{b.review.title||'Your experience'}</strong><p>{b.review.comment}</p></div>:<form className="review-form" onSubmit={review}><div className="form-group"><label>Rating</label><select name="rating" defaultValue="5"><option value="5">5 — Excellent</option><option value="4">4 — Very good</option><option value="3">3 — Good</option><option value="2">2 — Fair</option><option value="1">1 — Poor</option></select></div><div className="form-group"><label>Review title</label><input name="title" placeholder="A memorable local experience"/></div><div className="form-group"><label>What was your experience like?</label><textarea name="comment" rows={5} minLength={5} required/></div><button className="btn" disabled={busy}>{busy?'Publishing…':'Publish review'}</button></form>}</article>}</section>
 <aside><article className="detail-card sticky booking-actions-panel"><h3>Booking summary</h3><div className="price-lines"><span>Local service <strong>${b.subtotal.toFixed(2)}</strong></span><span>Platform fee <strong>${b.platform_fee.toFixed(2)}</strong></span><span className="price-total">Total <strong>${b.total.toFixed(2)}</strong></span></div>{canPay&&<button className="btn" onClick={pay} disabled={busy}>Pay securely</button>}<Link className="btn secondary" href={`/dashboard/messages?booking=${b.id}`}>Message {b.local_name.split(' ')[0]} {b.message_count?`(${b.message_count})`:''}</Link><Link className="btn secondary" href={`/locals/${b.local_slug}`}>View local profile</Link>{['pending','confirmed'].includes(b.status)&&!paid&&<button className="btn booking-cancel-btn" onClick={cancel} disabled={busy}>Cancel booking</button>}{paid&&['pending','confirmed'].includes(b.status)&&<p className="muted booking-policy-note">Paid bookings are cancelled through support so refund and booking status stay synchronized.</p>}</article></aside></div></>
}
function MeetingSummary({meeting}:{meeting:Meeting}){if(!meeting?.meeting_point_name&&!meeting?.meeting_address)return <p className="muted">Meeting point has not been finalized yet.</p>;return <div className="meeting-summary"><strong>{meeting.meeting_point_name||'Meeting point'}</strong>{meeting.meeting_address&&<p>{meeting.meeting_address}</p>}{meeting.meeting_instructions&&<small>{meeting.meeting_instructions}</small>}</div>}
function eventLabel(e:any){if(e.event_type==='requested')return 'Booking requested';if(e.event_type==='meeting_point_updated')return 'Meeting point updated';if(e.event_type.includes('status'))return `${e.from_status||'booking'} → ${e.to_status}`;if(e.event_type==='message')return 'New message';return e.event_type.replaceAll('_',' ')}
function paymentLabel(status:string){return ({manual:'Manual payment',unpaid:'Unpaid',checkout_open:'Checkout ready',processing:'Processing',paid:'Paid',failed:'Payment failed',refund_pending:'Refund pending',refunded:'Refunded'} as Record<string,string>)[status]||status.replaceAll('_',' ')}


