"use client";
import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import { authedFetch } from "@/lib/api";

type Meeting={meeting_point_name:string;meeting_address:string;meeting_instructions:string};
type Payment={status:string;required:boolean;currency:string;provider:string;mode:string};
type Booking={id:number;booking_date:string;start_time:string;end_time:string;guests:number;hours:number;message:string;subtotal:number;platform_fee:number;status:string;tourist_name:string;tourist_email:string;service_title:string;message_count:number;meeting_point:Meeting;timeline:any[];payment:Payment};
export default function Page(){
 const [items,setItems]=useState<Booking[]>([]);const [status,setStatus]=useState('Loading booking requests…');const [filter,setFilter]=useState('open');const [editing,setEditing]=useState<number|null>(null);
 async function load(){try{const r=await authedFetch('/api/local/bookings');if(!r.ok)throw new Error('Could not load booking requests');setItems(await r.json());setStatus('')}catch(e:any){setStatus(e.message||'Could not load bookings')}}
 useEffect(()=>{load()},[]);
 async function update(id:number,next:string){setStatus('Updating booking…');const r=await authedFetch(`/api/local/bookings/${id}`,{method:'PATCH',body:JSON.stringify({status:next})});const d=await r.json().catch(()=>({}));if(!r.ok){setStatus(d.detail||'Update failed');return}await load()}
 async function saveMeeting(id:number,meeting:Meeting){setStatus('Saving meeting point…');const r=await authedFetch(`/api/bookings/${id}/meeting-point`,{method:'PATCH',body:JSON.stringify({...meeting,latitude:null,longitude:null})});const d=await r.json().catch(()=>({}));if(!r.ok){setStatus(d.detail||'Could not save meeting point');return}setEditing(null);await load();setStatus('Meeting point saved.')}
 const shown=useMemo(()=>items.filter(x=>filter==='all'?true:filter==='open'?(x.status==='pending'||x.status==='confirmed'):x.status===filter),[items,filter]);
 return <><span className="eyebrow">Local workspace</span><h2>Booking requests</h2><p className="muted">Accept requests, manage the agreed meeting point and keep each booking in a valid lifecycle state.</p>{status&&<div className="notice">{status}</div>}
 <div className="filter-pills"><button className={filter==='open'?'active':''} onClick={()=>setFilter('open')}>Open ({items.filter(x=>x.status==='pending'||x.status==='confirmed').length})</button><button className={filter==='pending'?'active':''} onClick={()=>setFilter('pending')}>Pending</button><button className={filter==='confirmed'?'active':''} onClick={()=>setFilter('confirmed')}>Confirmed</button><button className={filter==='completed'?'active':''} onClick={()=>setFilter('completed')}>Completed</button><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>All</button></div>
 {shown.length?<div className="booking-request-list">{shown.map(b=><BookingCard key={b.id} b={b} editing={editing===b.id} setEditing={setEditing} update={update} saveMeeting={saveMeeting}/>)}</div>:<div className="empty">No bookings match this filter.</div>}</>
}

function BookingCard({b,editing,setEditing,update,saveMeeting}:{b:Booking;editing:boolean;setEditing:(id:number|null)=>void;update:(id:number,next:string)=>void;saveMeeting:(id:number,m:Meeting)=>void}){
 const [meeting,setMeeting]=useState<Meeting>(b.meeting_point||{meeting_point_name:'',meeting_address:'',meeting_instructions:''});
 useEffect(()=>setMeeting(b.meeting_point||{meeting_point_name:'',meeting_address:'',meeting_instructions:''}),[b.meeting_point]);
 const paymentStatus=b.payment?.status||'manual';
 const completionBlocked=Boolean(b.payment?.required&&paymentStatus!=='paid');
 return <article className="booking-request-card"><div className="booking-request-top"><div><div className="status-stack"><span className={`badge status-${b.status}`}>{b.status}</span><span className={`badge payment-${paymentStatus}`}>{paymentStatus.replaceAll('_',' ')}</span></div><h3>{b.service_title}</h3><p><strong>{b.tourist_name}</strong> · {b.tourist_email}</p></div><div className="booking-value"><strong>${b.subtotal.toFixed(2)}</strong><span>Local earnings</span></div></div><div className="booking-facts"><span><strong>Date</strong>{b.booking_date}</span><span><strong>Time</strong>{b.start_time}–{b.end_time}</span><span><strong>Duration</strong>{b.hours} hr</span><span><strong>Guests</strong>{b.guests}</span></div>{b.message&&<div className="traveler-note"><strong>Traveler note</strong><p>{b.message}</p></div>}
 <div className="meeting-panel"><div className="meeting-panel-head"><div><strong>Meeting point</strong><span>{b.meeting_point?.meeting_point_name||'Not finalized yet'}</span></div>{!['completed','cancelled','rejected'].includes(b.status)&&<button className="mini-btn secondary-mini" onClick={()=>setEditing(editing?null:b.id)}>{editing?'Close':'Set / edit'}</button>}</div>{!editing&&b.meeting_point?.meeting_point_name&&<div className="meeting-summary"><p>{b.meeting_point.meeting_address}</p>{b.meeting_point.meeting_instructions&&<small>{b.meeting_point.meeting_instructions}</small>}</div>}{editing&&<div className="meeting-edit-grid"><input value={meeting.meeting_point_name} onChange={e=>setMeeting({...meeting,meeting_point_name:e.target.value})} placeholder="Meeting point / landmark"/><input value={meeting.meeting_address} onChange={e=>setMeeting({...meeting,meeting_address:e.target.value})} placeholder="Address"/><textarea value={meeting.meeting_instructions} onChange={e=>setMeeting({...meeting,meeting_instructions:e.target.value})} placeholder="Exact instructions" rows={2}/><button className="mini-btn" onClick={()=>saveMeeting(b.id,meeting)}>Save meeting point</button></div>}</div>
 {completionBlocked&&b.status==='confirmed'&&<div className="notice payment-booking-note">Traveler payment must be confirmed before this booking can be completed.</div>}
 <div className="action-row booking-actions"><Link className="mini-btn secondary-mini" href={`/local-dashboard/messages?booking=${b.id}`}>Messages {b.message_count?`(${b.message_count})`:''}</Link>{b.status==='pending'&&<><button className="mini-btn" onClick={()=>update(b.id,'confirmed')}>Accept</button><button className="mini-btn danger-mini" onClick={()=>update(b.id,'rejected')}>Decline</button></>}{b.status==='confirmed'&&<><button className="mini-btn" disabled={completionBlocked} title={completionBlocked?'Traveler payment is required before completion':''} onClick={()=>update(b.id,'completed')}>Mark complete</button><button className="mini-btn danger-mini" onClick={()=>update(b.id,'cancelled')}>Cancel</button></>}</div></article>
}

