export type City = {
  countryCode: "GB" | "US";
  countrySlug: "uk" | "usa";
  countryName: string;
  slug: string;
  name: string;
  tagline: string;
  description: string;
  image: string;
};

export const cities: City[] = [
  {countryCode:"GB",countrySlug:"uk",countryName:"United Kingdom",slug:"london",name:"London",tagline:"Stories, markets and neighbourhoods beyond the postcard.",description:"Meet trusted London locals for private walks, food discoveries, photography, first-day orientation and flexible help shaped around your trip.",image:"https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1400&q=80"},
  {countryCode:"GB",countrySlug:"uk",countryName:"United Kingdom",slug:"manchester",name:"Manchester",tagline:"Music, football culture and northern character.",description:"Explore Manchester with people who know its neighbourhoods, culture and everyday favourites.",image:"https://images.unsplash.com/photo-1515586838455-8f8f940d6853?auto=format&fit=crop&w=1400&q=80"},
  {countryCode:"GB",countrySlug:"uk",countryName:"United Kingdom",slug:"birmingham",name:"Birmingham",tagline:"Canals, food and a city best understood locally.",description:"Find a Birmingham local for personal tours, practical trip help and authentic neighbourhood recommendations.",image:"/images/destinations/birmingham.jpg"},
  {countryCode:"GB",countrySlug:"uk",countryName:"United Kingdom",slug:"edinburgh",name:"Edinburgh",tagline:"Old streets, dramatic views and stories everywhere.",description:"Book a local in Edinburgh for history walks, family-friendly exploring, photography and personal trip planning.",image:"https://images.unsplash.com/photo-1506377585622-bedcbb027afc?auto=format&fit=crop&w=1400&q=80"},
  {countryCode:"GB",countrySlug:"uk",countryName:"United Kingdom",slug:"liverpool",name:"Liverpool",tagline:"Music, waterfront history and warm local energy.",description:"Discover Liverpool with locals who can tailor the city to your interests and pace.",image:"https://images.unsplash.com/photo-1579197120180-23066892f0eb?auto=format&fit=crop&w=1400&q=80"},
  {countryCode:"US",countrySlug:"usa",countryName:"United States",slug:"new-york",name:"New York",tagline:"Your own New York, one neighbourhood at a time.",description:"Hire a New York local for neighbourhood walks, photos, food, orientation and practical city help.",image:"https://images.unsplash.com/photo-1522083165195-3424ed129620?auto=format&fit=crop&w=1400&q=80"},
  {countryCode:"US",countrySlug:"usa",countryName:"United States",slug:"los-angeles",name:"Los Angeles",tagline:"Big city, many neighbourhoods — make it personal.",description:"Connect with LA locals for food, photography, culture and flexible private exploring.",image:"https://images.unsplash.com/photo-1534190760961-74e8c1c5c3da?auto=format&fit=crop&w=1400&q=80"},
  {countryCode:"US",countrySlug:"usa",countryName:"United States",slug:"miami",name:"Miami",tagline:"Beach energy, Latin culture and neighbourhood flavour.",description:"Meet Miami locals for cultural walks, food discovery, photography and travel help.",image:"https://images.unsplash.com/photo-1506966953602-c20cc11f75e3?auto=format&fit=crop&w=1400&q=80"},
  {countryCode:"US",countrySlug:"usa",countryName:"United States",slug:"las-vegas",name:"Las Vegas",tagline:"There is more to Vegas than the Strip.",description:"Find locals who can help you discover food, neighbourhoods, photo spots and practical Vegas advice.",image:"https://images.unsplash.com/photo-1581351721010-8cf859cb14a4?auto=format&fit=crop&w=1400&q=80"},
  {countryCode:"US",countrySlug:"usa",countryName:"United States",slug:"chicago",name:"Chicago",tagline:"Architecture, food and neighbourhood pride.",description:"Book Chicago locals for flexible walking experiences, food, photography and first-day orientation.",image:"https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1400&q=80"}
];

export const locals = [
  {id:1,slug:"james-wilson-london",name:"James Wilson",city:"London",country:"United Kingdom",countryCode:"GB",headline:"London storyteller & hidden-gems guide",languages:["English","Spanish"],rating:4.9,reviews:126,rate:32,verified:true,image:"https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=900&q=80",categories:["Tour Guide","Food Expert"],bio:"Born and raised in London, James loves showing visitors the character behind the landmarks: quiet lanes, old pubs, local markets and stories that rarely make it into guidebooks.",yearsLocal:18,response:"Usually within 1 hour",services:[{id:1,title:"Hidden London Walking Experience",category:"Tour Guide",duration:3,price:89,description:"A flexible private walk through famous streets and lesser-known corners."},{id:2,title:"London Food & Market Walk",category:"Food Expert",duration:2.5,price:78,description:"Taste local favourites while exploring one of London's best-known market areas."}]},
  {id:2,slug:"maya-carter-new-york",name:"Maya Carter",city:"New York",country:"United States",countryCode:"US",headline:"NYC photographer & neighbourhood local",languages:["English","French"],rating:4.8,reviews:84,rate:45,verified:true,image:"https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80",categories:["Photographer","Local Guide"],bio:"Maya combines street photography with an easygoing New York walk, helping visitors leave with great memories and photos rather than rushed snapshots.",yearsLocal:11,response:"Usually within 2 hours",services:[{id:3,title:"NYC Photo Walk",category:"Photographer",duration:2,price:110,description:"A relaxed private photo walk through the neighbourhoods you choose."},{id:4,title:"Local NYC Orientation",category:"Local Guide",duration:2,price:80,description:"Get comfortable with transit, neighbourhoods and practical local tips on your first day."}]},
  {id:3,slug:"olivia-hart-edinburgh",name:"Olivia Hart",city:"Edinburgh",country:"United Kingdom",countryCode:"GB",headline:"Edinburgh history lover & family-friendly local",languages:["English","German"],rating:5.0,reviews:58,rate:29,verified:true,image:"https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=80",categories:["Tour Guide","Family Friendly"],bio:"Olivia creates friendly, flexible walks for couples and families who want history without a classroom feel.",yearsLocal:14,response:"Usually within 3 hours",services:[{id:5,title:"Old Town Stories",category:"Tour Guide",duration:2.5,price:72,description:"A private Old Town walk shaped around your pace and interests."}]},
  {id:4,slug:"daniel-brooks-miami",name:"Daniel Brooks",city:"Miami",country:"United States",countryCode:"US",headline:"Miami food, culture & bilingual local",languages:["English","Spanish"],rating:4.9,reviews:69,rate:38,verified:true,image:"https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=80",categories:["Food Expert","Local Guide"],bio:"Daniel helps visitors discover Miami beyond the beach, with a focus on neighbourhood culture and casual local food.",yearsLocal:16,response:"Usually within 1 hour",services:[{id:6,title:"Miami Local Food Explorer",category:"Food Expert",duration:3,price:98,description:"A private, flexible food-focused local experience."}]}
];

export const serviceCategories = ["Tour Guide","Photographer","Food Expert","Local Guide","Interpreter","Trip Planner","Shopping Companion","Airport Assistance"];

export const blogPosts = [
 {slug:"how-to-hire-a-local-guide-london",title:"How to Hire a Local Guide in London: What to Look For",excerpt:"A practical checklist for choosing a trustworthy local, agreeing on the plan and getting more value from a private experience.",date:"2026-08-10",category:"London",image:"https://images.unsplash.com/photo-1486299267070-83823f5448dd?auto=format&fit=crop&w=1200&q=80"},
 {slug:"first-time-new-york-local-tips",title:"First Time in New York 12 Local Tips That Make the Trip Easier",excerpt:"From neighbourhood planning to subway habits, these are the small things that make a first New York trip smoother.",date:"2026-08-08",category:"New York",image:"https://images.unsplash.com/photo-1496588152823-86ff7695e68f?auto=format&fit=crop&w=1200&q=80"},
 {slug:"private-guide-vs-group-tour",title:"Private Local vs Group Tour: Which Is Better for Your Trip?",excerpt:"Compare flexibility, price, pace and personalisation before deciding how you want to explore a city.",date:"2026-08-05",category:"Travel Planning",image:"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80"}
];

